name: Shell Commands flow

#on: [push,pull_request]
on: 
  push: 
  pull_request:
    types:
      - "opened"
      - "closed"
      - "assigned"
      - "reopened"
  schedule:
    - cron: "1 * * * *"

jobs: 
  run-shell-commond: 
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Git Hub Action Test"
      - name: multiline script 
        run: |
          node -v
          npm -v
      - name: Python Commond 
        run: |
          import platform
          print (platform.processor())
        shell: python
  run-windows-commond:
    needs: ["run-shell-commond"] # used to run jobs sequentially #
    runs-on: windows-latest
    steps:
      - name: Directory Powershell. 
        run: Get-Location # This is a powerShell Command
      - name: Directory Bash
        run : pwd
        shell: bash
